#!/bin/bash

az account get-access-token > /dev/null

if [ $? -eq 0 ]; then
    echo 'Azure login is valid'
    exit 0
else
    echo 'Please login to azure portal...'
    az login --only-show-errors > /dev/null
    az account set --subscription $AZURE_SUBSCRIPTION > /dev/null
fi