#!/bin/bash

# Ensure git repo
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    echo "Not a git repository. Please run this script inside a git repository."
    exit 1
fi


url=$(git remote get-url origin)

project=$(echo "$url" | cut -d: -f2-)

# Check if the project is not empty
if [[ -z "$project" ]]; then
    echo "The project name is empty. Please set a valid remote URL."
    exit 1
fi

git remote set-url origin "git@github.com:$project"