#! /bin/sh

scripts/devbox-setup.sh
devbox run -- scripts/macos-setup.sh
devbox run -- scripts/homebrew-setup.sh
devbox run -- scripts/zsh-setup.sh
devbox run -- scripts/vscode-setup.sh
devbox run -- scripts/k9s-setup.sh