#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
marker='<!-- Generated from .agents/profiles. Do not edit this file directly. -->'
failed=0

check_body() {
  adapter=$1
  profile=$2

  if ! awk -v marker="$marker" '
    $0 == marker { found = 1; next }
    found { print }
  ' "$adapter" | diff -u "$profile" -; then
    printf '%s\n' "Generated body differs from $profile: $adapter" >&2
    failed=1
  fi
}

check_field() {
  adapter=$1
  field=$2

  if ! grep -Fqx "$field" "$adapter"; then
    printf '%s\n' "Missing expected field in $adapter: $field" >&2
    failed=1
  fi
}

check_body "$root/.config/opencode/agents/fast.md" "$root/.agents/profiles/fast.md"
check_body "$root/.config/opencode/agents/genius.md" "$root/.agents/profiles/genius.md"
check_body "$root/.claude/agents/fast.md" "$root/.agents/profiles/fast.md"
check_body "$root/.claude/agents/genius.md" "$root/.agents/profiles/genius.md"
check_body "$root/.copilot/agents/fast.agent.md" "$root/.agents/profiles/fast.md"
check_body "$root/.copilot/agents/genius.agent.md" "$root/.agents/profiles/genius.md"

check_field "$root/.config/opencode/agents/fast.md" 'model: github-copilot/gpt-5.6-luna'
check_field "$root/.config/opencode/agents/fast.md" 'mode: subagent'
check_field "$root/.config/opencode/agents/fast.md" 'steps: 8'
check_field "$root/.config/opencode/agents/fast.md" '  edit: deny'
check_field "$root/.config/opencode/agents/fast.md" '  bash: deny'
check_field "$root/.config/opencode/agents/fast.md" '  task: deny'
check_field "$root/.config/opencode/agents/fast.md" '  webfetch: deny'
check_field "$root/.config/opencode/agents/fast.md" '  websearch: deny'
check_field "$root/.config/opencode/agents/genius.md" 'model: github-copilot/claude-opus-4.8'
check_field "$root/.config/opencode/agents/genius.md" 'mode: subagent'
check_field "$root/.config/opencode/agents/genius.md" 'steps: 40'
check_field "$root/.config/opencode/agents/genius.md" '  task: deny'
check_field "$root/.claude/agents/fast.md" 'model: haiku'
check_field "$root/.claude/agents/fast.md" 'tools: Read, Glob, Grep'
check_field "$root/.claude/agents/fast.md" 'maxTurns: 8'
check_field "$root/.claude/agents/genius.md" 'model: opus'
check_field "$root/.claude/agents/genius.md" 'tools: Read, Glob, Grep, Edit, Write, Bash'
check_field "$root/.claude/agents/genius.md" 'maxTurns: 40'
check_field "$root/.claude/agents/genius.md" 'permissionMode: default'
check_field "$root/.copilot/agents/fast.agent.md" 'model: "GPT-5.6 Luna (copilot)"'
check_field "$root/.copilot/agents/fast.agent.md" 'tools: ["search/codebase", "search/usages"]'
check_field "$root/.copilot/agents/fast.agent.md" 'user-invocable: true'
check_field "$root/.copilot/agents/fast.agent.md" 'disable-model-invocation: false'
check_field "$root/.copilot/agents/fast.agent.md" 'agents: []'
check_field "$root/.copilot/agents/genius.agent.md" 'model: "Claude Opus 4.8 (copilot)"'
check_field "$root/.copilot/agents/genius.agent.md" 'tools: ["agent", "edit", "search/codebase", "search/usages", "runCommands", "web/fetch"]'
check_field "$root/.copilot/agents/genius.agent.md" 'user-invocable: true'
check_field "$root/.copilot/agents/genius.agent.md" 'disable-model-invocation: false'
check_field "$root/.copilot/agents/genius.agent.md" 'agents: ["Fast"]'

exit "$failed"
