#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

write_adapter() {
  output=$1
  header=$2
  profile=$3

  mkdir -p "$(dirname -- "$output")"
  {
    printf '%s\n' "$header"
    printf '%s\n' '<!-- Generated from .agents/profiles. Do not edit this file directly. -->'
    cat "$profile"
  } > "$output"
}

write_adapter "$root/.config/opencode/agents/fast.md" '---
description: Fast low-cost subagent for bounded, read-only searches, summaries, extraction, and classification. Use proactively for narrow tasks that do not need edits, shell commands, or high-risk judgment.
mode: subagent
model: github-copilot/gpt-5.6-luna
steps: 8
permission:
  edit: deny
  bash: deny
  task: deny
  webfetch: deny
  websearch: deny
---' "$root/.agents/profiles/fast.md"

write_adapter "$root/.config/opencode/agents/genius.md" '---
description: Strongest-tier subagent for complex execution: multi-file implementation, difficult debugging, migrations, security-sensitive work, and high-risk infrastructure changes. Use proactively when a high-quality first attempt matters.
mode: subagent
model: github-copilot/claude-opus-4.8
steps: 40
permission:
  task: deny
---' "$root/.agents/profiles/genius.md"

write_adapter "$root/.claude/agents/fast.md" '---
name: fast
description: Fast low-cost subagent for bounded, read-only searches, summaries, extraction, and classification. Use proactively for narrow tasks that do not need edits, shell commands, or high-risk judgment.
tools: Read, Glob, Grep
model: haiku
maxTurns: 8
---' "$root/.agents/profiles/fast.md"

write_adapter "$root/.claude/agents/genius.md" '---
name: genius
description: Strongest-tier subagent for complex execution: multi-file implementation, difficult debugging, migrations, security-sensitive work, and high-risk infrastructure changes. Use proactively when a high-quality first attempt matters.
tools: Read, Glob, Grep, Edit, Write, Bash
model: opus
maxTurns: 40
permissionMode: default
---' "$root/.agents/profiles/genius.md"

write_adapter "$root/.copilot/agents/fast.agent.md" '---
name: Fast
description: Fast low-cost agent for bounded, read-only searches, summaries, extraction, and classification. Use for narrow tasks that do not need edits, terminal commands, or high-risk judgment.
tools: ["search/codebase", "search/usages"]
model: "GPT-5.6 Luna (copilot)"
user-invocable: true
disable-model-invocation: false
agents: []
---' "$root/.agents/profiles/fast.md"

write_adapter "$root/.copilot/agents/genius.agent.md" '---
name: Genius
description: Strongest-tier agent for complex execution: multi-file implementation, difficult debugging, migrations, security-sensitive work, and high-risk infrastructure changes. Use proactively when a high-quality first attempt matters.
tools: ["agent", "edit", "search/codebase", "search/usages", "runCommands", "web/fetch"]
model: "Claude Opus 4.8 (copilot)"
user-invocable: true
disable-model-invocation: false
agents: ["Fast"]
---' "$root/.agents/profiles/genius.md"
